name: Deploy

on:
  - workflow_dispatch

jobs:
  build_image:
    name: "Build & Push Image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout Repository"

      - name: "Push to GCR GitHub Action"
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
            gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
            registry: eu.gcr.io
            project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
            image_name: node-server
            image_tag: latest,v1
            dockerfile: ./server/Dockerfile
